#!/bin/bash
set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Configuration
VERSIONS_DIR="${HOME}/versions/generators"

# Logging functions
log_info() { echo -e "${GREEN}INFO: $1${NC}" >&2; }
log_warn() { echo -e "${YELLOW}WARN: $1${NC}" >&2; }
log_error() { echo -e "${RED}ERROR: $1${NC}" >&2; }

# Print header
echo "# Development Environment Versions"
echo
echo "Generated on: $(date '+%Y-%m-%d %H:%M:%S')"
echo

# Make scripts executable
chmod +x "${VERSIONS_DIR}"/*.sh

# Execute each generator script
for script in "${VERSIONS_DIR}"/*.sh; do
    if [[ -x "${script}" ]]; then
        script_name=$(basename "${script}")
        
        # Print section separator
        echo "---"
        echo

        # Execute script and capture output
        if ! output=$("${script}"); then
            log_error "${script_name} failed"
            continue
        fi

        # Print script output
        echo "${output}"
        echo

    fi
done

# Print footer
echo "---"
echo
echo "Generated by \`generate-versions.sh\`"