name: jupyter-env

dependencies:
  - python=3.11
  ## Core Jupyter packages
  - jupyter
  - jupyterlab
  - nb_conda_kernels
  - nbgitpuller
  - ipykernel
  - ipython
  
  ## Data Science packages
  #- numpy
  #- pandas
  #- matplotlib
  #- seaborn
  #- scikit-learn

  ## Additional utilities
  - pip