channels:
- conda-forge
- nodefaults
- terradue

dependencies:
- jupyter-server-proxy
- jupyterhub
# - jupyterlab
- jupyterlab-git
- nb_conda_kernels
- nbgitpuller
- pandas
- websockify
- seaborn
- jupyterlab_code_formatter