name: Multi-Arch CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 02 * * *'    
  push:
      
jobs:
  build:
    name: build-push-updaterepo
    uses: ebpro/gh-actions-shared-docker/.github/workflows/ci-shareable-docker-qemu.yml@develop
    with:
        runs-on: arc-runner-set-compute-lsis
        env-list: >
          [ "" ]
    secrets: inherit
    
